# -*- coding: utf-8 -*-
"""IPL Data Analysis 2008-2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ppekPpKrkpmT3jUNTnP_0PrOs5jgXpq
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")
sns.set_theme(
    style="whitegrid",
    context="talk",   # great for presentations
    palette="muted"
)

plt.style.use('fivethirtyeight')

"""# **Load the Data Set**"""

matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

"""# **Filtering Matches**"""

matches.info()

deliveries.info()

"""# **Season**"""

matches["season"].unique()

# Function to convert season to a single year


def normalize_season(season):
    if season == "2020/21":  # special case
        return 2020
    elif "/" in season:
        start, end = season.split("/")  # later year for other multi-year seasons
        return int(start[:2] + end)
    else:
        return int(season)  # already single year



# Apply to the 'season' column
matches['season'] = matches['season'].map(normalize_season)

matches["season"].unique()

matches["season"].value_counts().reset_index(name='total_matches').sort_values(by='season')

"""# **City**"""

matches['city'].value_counts()

# Remove leading/trailing spaces and invisible characters
matches['city'] = matches['city'].str.strip().str.replace(r'\s+', ' ', regex=True)

# Replace Bengaluru with Bangalore
matches['city'] = matches['city'].replace({'Bengaluru': 'Bangalore'})

# # Check if replacement worked
matches['city'].value_counts()

matches.head()

"""# **Team1 and Team2**"""

matches["team1"].unique()

team_corrections = {
    'Kings XI Punjab': 'Punjab Kings',
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'
}


matches['team1'] = matches['team1'].replace(team_corrections)
matches['team2'] = matches['team2'].replace(team_corrections)

matches["team1"].unique()

matches["team1"].value_counts()

matches["team2"].value_counts()

"""# **Toss Decision**"""

matches["toss_decision"].value_counts()

matches["winner"].unique()

team_corrections = {
    'Kings XI Punjab': 'Punjab Kings',
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'
}


matches['toss_winner'] = matches['toss_winner'].replace(team_corrections)
matches['winner'] = matches['winner'].replace(team_corrections)

matches["toss_winner"].unique()

matches_played = pd.concat([matches['team1'], matches['team2']]).value_counts().reset_index()
matches_played

match_wins = matches['winner'].value_counts().reset_index()
match_wins

toss_wins = matches['toss_winner'].value_counts().reset_index()
toss_wins

toss_match_wins = matches[matches['toss_winner'] == matches['winner']]['toss_winner'].value_counts().reset_index()
toss_match_wins

# Rename columns
matches_played.columns = ['Team', 'Matches_Played']
match_wins.columns = ['Team', 'Match_Wins']
toss_wins.columns = ['Team', 'Toss_Wins']
toss_match_wins.columns = ['Team', 'Toss_And_Match_Wins']

analysis = pd.merge(matches_played, match_wins, on='Team', how='outer')
analysis = pd.merge(analysis, toss_wins, on='Team', how='outer')
analysis = pd.merge(analysis, toss_match_wins, on='Team', how='outer')
analysis = analysis.sort_values(by='Matches_Played', ascending=False)
analysis = analysis.fillna(0)
analysis

"""# **Filling NA Values**"""

matches.isnull().sum()

matches[matches['city'].isna()].index

matches.iloc[196]

matches['city'] = matches['city'].fillna('Unknown')

matches['city'].isnull().sum()

matches['city'].unique()

matches["method"].unique()

matches["method"] = matches["method"].fillna("Non D/L")

matches["method"].unique()

deliveries.isnull().sum()

deliveries["batting_team"].unique()

deliveries["bowling_team"].unique()

team_corrections = {
    'Kings XI Punjab': 'Punjab Kings',
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'
}


deliveries["batting_team"] = deliveries["batting_team"].replace(team_corrections)
deliveries["bowling_team"] = deliveries["bowling_team"].replace(team_corrections)

deliveries["bowling_team"].unique()

"""# **Analysis**"""

toss_decision_counts = matches["toss_decision"].value_counts()


plt.pie(toss_decision_counts, labels=toss_decision_counts.index, autopct='%1.2f%%', startangle=90)
plt.title("Toss Decision")
plt.show()

sort_team_name = {
    'Sunrisers Hyderabad': 'SRH',
    'Rising Pune Supergiants': 'RPS',
      'Kolkata Knight Riders': 'KKR',
      'Punjab Kings': 'PK',
      'Royal Challengers Bengaluru': 'RCB',
      'Mumbai Indians': 'MI',
      'Delhi Capitals': 'DC',
      'Gujarat Lions': 'GL',
      'Chennai Super Kings': 'CSK',
      'Rajasthan Royals': 'RR',
      'Gujarat Titans': 'GT',
      'Lucknow Super Giants': 'LSG',
      'Deccan Chargers': 'DChargers',
      'Pune Warriors': 'PW',
      'Kochi Tuskers Kerala': 'KTK'
}

analysis['Team'] = analysis['Team'].map(sort_team_name)
analysis

plt.figure(figsize=(13,6))

plt.scatter(analysis['Team'],analysis['Matches_Played'],label='Matches Played',s=100,alpha=1)
plt.plot(analysis['Team'],analysis['Match_Wins'],marker='o',label='Match_Wins',color='green')
plt.scatter(analysis['Team'],analysis['Toss_Wins'],label='Toss_Wins',s=100,alpha=1)
plt.plot(analysis['Team'],analysis['Toss_And_Match_Wins'],marker='o',label='Toss_And_Match_Wins',color='purple')

plt.title("Team Performance Analysis")
plt.xlabel("Team")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.legend(title="Metrics")

plt.show()

"""# **Impact of Toss on Team Success Rate**"""

analysis['Success_Rate_%'] = (analysis['Match_Wins'] / analysis['Matches_Played']) * 100
analysis['Toss_Win_Impact_%'] = (analysis['Toss_And_Match_Wins'] / analysis['Toss_Wins']) * 100
analysis[['Team', 'Success_Rate_%','Toss_Win_Impact_%']]

plt.figure(figsize=(12,4))

plt.scatter(analysis['Team'], analysis['Success_Rate_%'],label='Success_Rate_%',s=100,alpha=1)
plt.scatter(analysis['Team'], analysis['Toss_Win_Impact_%'],label='Toss_Win_Impact_%',s=100,alpha=1)

plt.title("Impact of Toss on Team Success Rate")
plt.xlabel("Team")
plt.ylabel("Success Rate (%)")
plt.legend()
plt.xticks(rotation=90) # Rotate x-axis labels for better readability
plt.show()

"""# **Most Titles Wins**"""

titles_wins = matches.groupby('season')[['season','winner']].tail(1)['winner'].value_counts()
titles_wins

plt.figure(figsize=(12,6))

color=["magenta", "lime", "green", "yellow", "navy", "purple", "cyan", "teal"]

sns.barplot(x=titles_wins.index,y=titles_wins.values, palette=color)

plt.title('Most Title Wins')
plt.xlabel('Teams')
plt.ylabel('Number of Season Won')
plt.xticks(rotation = 60)
plt.tight_layout()
plt.show()

"""# **Top 10 Players with Most Runs**"""

players_runs = deliveries.groupby('batter')['batsman_runs'].sum().reset_index(name='Runs')
players_runs.sort_values(by='Runs', ascending=False).head(10)

deliveries['batsman_runs'] = deliveries['batsman_runs'].fillna(0)

deliveries['batsman_runs'] = deliveries['batsman_runs'].astype(int)

batsman_total_score = deliveries.groupby('batter')['batsman_runs'].sum().reset_index(name='Runs')
batsman_total_score = batsman_total_score.sort_values(by='Runs', ascending=False)
top_10_players = batsman_total_score.head(10)
top_10_players

plt.figure(figsize=(12,6))

colors = [ "red", "blue", "green", "orange", "purple", "olive", "magenta", "yellow", "teal", "navy", "gray", "cyan", "brown", "pink", "gold"]
sns.barplot(data=top_10_players, x='batter', y='Runs', palette=colors)

plt.title('Top 10 batmen in IPL - Seasons till 2025')
plt.xlabel('Batsmen')
plt.ylabel('Runs Scored')
plt.xticks(rotation= 60)
plt.tight_layout()
plt.show()

"""# **Top 10 Best Performances in a Match**"""

batsmen_highest_score = deliveries.groupby(['match_id', 'batter'])['batsman_runs'].sum().reset_index(name='Innings_Runs')
batsmen_highest_score = batsmen_highest_score.sort_values(by='Innings_Runs', ascending=False).head(10)
batsmen_highest_score

batsmen_balls_faced = deliveries.groupby(['match_id', 'batter'])['ball'].count().reset_index(name='Balls_Faced')
batsmen_balls_faced

batsmen_performance = pd.merge(batsmen_highest_score, batsmen_balls_faced[['match_id', 'batter','Balls_Faced']], how='inner', on=['match_id', 'batter'])
batsmen_performance

strike_rate = np.round(batsmen_performance['Innings_Runs']/batsmen_performance['Balls_Faced']*100, 2).reset_index(name='Strike_Rate')
strike_rate

batsmen_performance['Strike_Rate'] = strike_rate['Strike_Rate']
batsmen_performance

plt.figure(figsize=(12,6))

plt.scatter(batsmen_performance['batter'], batsmen_performance['Strike_Rate'], label='Strike Rate %', s=100, alpha=1)
plt.scatter(batsmen_performance['batter'], batsmen_performance['Innings_Runs'], label='Runs', s=100, alpha=1)

plt.title('Top 10 Best Performances in a Match')
plt.xlabel('Batsmen')
plt.ylabel('Inning Score / Strike Rate')
plt.xticks(rotation=45)
plt.tight_layout()
plt.legend()
plt.show()

"""# **Top 10 Best Bowlers**"""

bowling_wickets = deliveries[deliveries['dismissal_kind'] != 'run out'] # dismissal is not runout

top_bowlers = bowling_wickets.groupby('bowler')['dismissal_kind'].count().reset_index(name='Wickets')
top_bowlers = top_bowlers.sort_values(by='Wickets', ascending=False).head(10)
top_bowlers

plt.figure(figsize=(12,6))

plt.plot(top_bowlers['bowler'],top_bowlers['Wickets'], marker= 'o',color='red',ms=15)

plt.title('Top 10 bowlers in IPL - Seasons till 2025')
plt.xlabel('Bowlers')
plt.ylabel('Wickets Taken')
plt.xticks(rotation = 45)
plt.tight_layout()
plt.show()

"""# **Top 10 Bowling Performances**"""

top_match_wickets = deliveries.groupby(['match_id', 'bowler'])['dismissal_kind'].count().reset_index(name='Wickets').sort_values(by='Wickets', ascending=False).head(10)
top_match_wickets

match_bowler_runs = deliveries.groupby(['match_id', 'bowler'])['total_runs'].sum().reset_index(name='Runs_Conceded')
match_bowler_runs

top_bowler_performance = pd.merge(top_match_wickets, match_bowler_runs, how='inner', on=['match_id', 'bowler'])
top_bowler_performance

top_bowler_performance[['Wickets', 'Runs_Conceded']].dtypes

top_bowler_performance['Runs_Per_Wickets'] = np.round(top_bowler_performance['Runs_Conceded']/top_bowler_performance['Wickets'], 2)
top_bowler_performance

plt.figure(figsize=(12,6))

plt.scatter(top_bowler_performance['bowler'],top_bowler_performance['Wickets'],label='Wickets',s=200,alpha=1, color='green')
plt.plot(top_bowler_performance['bowler'],top_bowler_performance['Runs_Per_Wickets'],marker='s',label='Runs per Wicket', color="magenta")

plt.title('Top 10 Best Bowling Performances in a Match')
plt.xlabel('Bowlers')
plt.ylabel('Runs per Wicket / Wickets Taken')
plt.legend()
plt.xticks(rotation = 45)
plt.tight_layout()
plt.show()

"""# **Top 10 Cities for Matches**"""

top_cities = matches['city'].value_counts().reset_index(name='Match_Count').head(10)
top_cities

plt.figure(figsize=(8,7))
plt.pie(top_cities['Match_Count'], labels=top_cities['city'], autopct='%1.2f%%', wedgeprops=dict(edgecolor='black'))
plt.title('Top Cities that have hosted IPL Matches')
plt.tight_layout()
plt.show()

"""# **Top Dismissal Kind**"""

top_dismissal = deliveries['dismissal_kind'].value_counts().reset_index(name='Count').head(10)
top_dismissal

plt.figure(figsize=(12,6))

colors = [ "red", "blue", "green", "orange", "purple", "olive", "magenta", "yellow", "teal", "navy", "gray", "cyan", "brown", "pink", "gold"]
plt.bar(top_dismissal['dismissal_kind'], top_dismissal['Count'], color=color)
plt.title('Top Dismissal Kind')
plt.xlabel('Dismissal Kind')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# **Top 10 Fielders**"""

top_fielders = deliveries['fielder'].value_counts().reset_index(name='Count').head(10)
top_fielders

plt.figure(figsize=(12,6))

colors = ["yellow", "teal", "navy", "gray", "cyan", "brown", "pink", "gold", "green", "orange", "purple", "olive", "magenta"]
plt.bar(top_fielders['fielder'], top_fielders['Count'], color=colors)

plt.title('Top 10 Fielders')
plt.xlabel('Fielders')
plt.ylabel('Number of Catches & Run out')
plt.xticks(rotation = 90)
plt.tight_layout()
plt.show()

"""# **Toss Impact Analysis**"""

toss_win_match_win = matches[matches['toss_winner'] == matches['winner']]

print("Matches won after winning toss:", toss_win_match_win.shape[0])
print("Total matches:", matches.shape[0])

toss_win_percentage = (toss_win_match_win.shape[0] / matches.shape[0]) * 100
print("Toss win impact (%):", round(toss_win_percentage,2))

toss_decision_win = matches[matches['toss_winner'] == matches['winner']]

decision_analysis = toss_decision_win['toss_decision'].value_counts()

decision_analysis

decision_analysis.plot(kind='bar', color=['orange','skyblue'])

plt.title("Toss Decision Impact on Match Result")
plt.xlabel("Toss Decision")
plt.ylabel("Matches Won")
plt.show()

"""# **Analysis by Over**"""

over_summary = deliveries.groupby('over')[['total_runs','is_wicket','extra_runs','batsman_runs']].sum()
over_summary

fig, axes = plt.subplots(2,2,figsize=(20,10))
fig.suptitle('Over by Over Analysis')

# axes[0,0].figure(figsize=(10,5))
axes[0,0].plot(over_summary.index,over_summary['total_runs'],marker='o')
axes[0,0].set_title('Runs Scored Per Over')
axes[0,0].set_xlabel('Over')
axes[0,0].set_ylabel('Runs')

# axes[0,1].figure(figsize=(10,5))
axes[0,1].plot(over_summary.index,over_summary['is_wicket'],marker='o')
axes[0,1].set_title('wickets Per Over')
axes[0,1].set_xlabel('Over')
axes[0,1].set_ylabel('Wickets')

# axes[1,0].figure(figsize=(10,5))
axes[1,0].plot(over_summary.index,over_summary['extra_runs'],marker='o')
axes[1,0].set_title('Extra Runs Scored Per Over')
axes[1,0].set_xlabel('Over')
axes[1,0].set_ylabel('Extra Runs')

# axes[1,1].figure(figsize=(10,5))
axes[1,1].plot(over_summary.index,over_summary['batsman_runs'],marker='o')
axes[1,1].set_title('Batsman Runs Scored Per Over')
axes[1,1].set_xlabel('Over')
axes[1,1].set_ylabel('Batsman Runs')

plt.tight_layout()
plt.show()

powerplay = over_summary.loc[0:5]['total_runs'].sum()
middle_overs = over_summary.loc[6:14]['total_runs'].sum()
death_overs = over_summary.loc[15:19]['total_runs'].sum()

print("Powerplay Runs:", powerplay)
print("Middle Overs Runs:", middle_overs)
print("Death Overs Runs:", death_overs)

plt.figure(figsize=(10,5))

phases = ['Powerplay', 'Middle Overs', 'Death Overs']
runs = [powerplay, middle_overs, death_overs]

sns.barplot(x=['Powerplay', 'Middle Overs', 'Death Overs'], y=[powerplay, middle_overs, death_overs])

plt.title('Powerplay vs Middle Overs vs Death Overs')
plt.xlabel('Runs')
plt.ylabel('Over')
plt.show()

over_summary.plot(figsize=(12,6), title="Over Wise Match Analysis")

corr = deliveries[['total_runs','batsman_runs','extra_runs','over','ball']].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap of Match Variables")
plt.show()

venue_runs = matches.pivot_table(
    values='target_runs',
    index='venue',
    columns='winner',
    aggfunc='count'
)

plt.figure(figsize=(12,8))
sns.heatmap(venue_runs, cmap='coolwarm')
plt.title("Team Performance by Venue")
plt.show()

pivot_runs = deliveries.pivot_table(
    values='total_runs',
    index='over',
    columns='batting_team',
    aggfunc='sum'
)

plt.figure(figsize=(12,6))
sns.heatmap(pivot_runs, cmap='YlOrRd')
plt.title("Runs Distribution by Over and Team")
plt.show()

